### ISSUE TITLE
Keras training speed on ImageNet and Resnet50

### ISSUE THREAD

**Issue by roywei** [wichtounet/frameworks#3]
Hi
I came from [this issue](https://github.com/keras-team/keras/issues/6486)
I am using your script to do benchmark on Keras with TensorFlow backend on imagenet dataset and resnet50 model, and I am observing significant slow speed comparing to pure tensorflow.  I am using AWS p3.8xlarge instance with 4GPUs (used [multi_gpu_model](https://keras.io/utils/#multi_gpu_model)) batch size 128, and the speed is only 177 imgs/second, while tensorflow is around 900 imgs/second.
Do you have any insights? thanks!

**Comment by wichtounet** [comment]
Hi, 

Unfortunately, I have no experience with the multi GPU model. 

Did you check the GPU Utilization to see if there is a difference ? Both should  have around the same GPU utilization. That will at least give an idea if all the GPUs are used. 

Can you share your code so I can take a look ? 

Thanks

Baptiste

**Comment by roywei** [comment]
Yes,  I used multi_gpu_model in keras util, and all GPUs are utilized, but I think it's not very efficient compare to pure TensorFlow.
Here is my script for ImageNet: https://github.com/roywei/keras/blob/benchmark/benchmark/scripts/benchmark_imagenet_resnet.py
and for Synthetic data:
https://github.com/roywei/benchmarks/blob/keras-mxnet-benchmark/scripts/keras_benchmarks/models/resnet50_benchmark.py

**Comment by wichtounet** [comment]
Hi, 

I just took a look at your second script (the first link does not work). 

I don't see anything wrong, it should be good. Especially since you generate data randomly and in memory, this should not be a bottleneck. 

Probably a dumb question, but are you sure your code goes into: model = keras.utils.multi_gpu_model(model, gpus=gpus) ?

I have seen examples where the model is created inside: 
with tf.device("/cpu:0"):

and then only the multi_gpu_model is created on GPU. Did you try such a thing ? 

Are you sure your are using the same batch size ? Maybe TF uses 32 per GPU and keras uses 32 total ? You can try 32 * gpus on Keras. 

Aside from these small ideas, I don't know :s
